### ISSUE TITLE
jartighten 

### ISSUE THREAD

**Issue by CFoit** [NeRdTheNed/JarTighten#2]
I can't make it to work yet with Command Line.
Most of the time it gives the msg: "The system cannot find the file specified" , while all the files are in the same folder with the cmd.exe.
Some time it show no error but no job is done.
I have tried a variety combination of  suggested parameters  but no luck.
Can somebody please show me an simple example of cmd command assuming that the filename to be optimized is "file_X.jar" and output is "file_Y.jar" ?
Thank you.

**Comment by NeRdTheNed** [comment]
Hi @CFoit, to use JarTighten 1.2.12 (the current release) to optimise `file_X.jar` and output the optimised file as `file_Y.jar` from your example, you would run `java -jar JarTighten-1.2.12-all.jar file_X.jar file_Y.jar`. If you need to overwrite an existing `file_Y.jar`, use `java -jar JarTighten-1.2.12-all.jar --overwrite file_X.jar file_Y.jar` (this will delete `file_Y.jar` if it already exists). Hope this helps!

**Comment by CFoit** [comment]
Thank you @NeRdTheNed for the solution, you was nice.
Now, the job is done but it throwing some Warnings.
Maybe that has no relation with you but you can take a look anyway.:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by software.coley.lljzip.util.FileMapUtil (file:/C:/Users ..../java_create_environment/JarTighten-1.2.12-all.jar) to method sun.nio.ch.FileChannelImpl.map0(int,long,long)
WARNING: Please consider reporting this to the maintainers of software.coley.lljzip.util.FileMapUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release.

Anyway,  Again thank you vary much

**Comment by NeRdTheNed** [comment]
> Thank you @NeRdTheNed for the solution, you was nice. Now, the job is done but it throwing some Warnings. Maybe that has no relation with you but you can take a look anyway.: WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access by software.coley.lljzip.util.FileMapUtil (file:/C:/Users ..../java_create_environment/JarTighten-1.2.12-all.jar) to method sun.nio.ch.FileChannelImpl.map0(int,long,long) WARNING: Please consider reporting this to the maintainers of software.coley.lljzip.util.FileMapUtil WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release.
> 
> Anyway, Again thank you vary much

All good, happy to help! Those warnings are related to the library JarTighten uses for parsing Zip files, I'll need to address updating it at some point. The version I use is slightly out of date because newer versions of the library require very recent versions of Java, and JarTighten currently uses an older version of Java.
